EX-83 & 92 Omeka-S data persistence and add-ons
tulibraries/tul_omeka-s pull request #1
Opened 2021-10-07 16:21 UTC by nomadicoder

2021-10-07 19:22 UTC, sensei100 commented on README.md
> +# Mounted Volumes for Persistence
@nomadicoder It might be nice to add this to the kubernetes documentation as well.

2021-10-07 19:22 UTC, sensei100 commented on README.md
> +- Rancho Workload Dashboard
```suggestion
- Rancher Workload Dashboard
```

2021-10-07 19:23 UTC, sensei100 commented on README.md
> +1. In browser, visit the Rancho Workload Dashboard
```suggestion
1. In browser, visit the Rancher Workload Dashboard
```

2021-10-07 19:24 UTC, sensei100 requested changes
@nomadicoder Looks good, maybe just a couple of typos for the dashboard name?

2021-10-07 20:04 UTC, cdoyle-temple commented on README.md
> +- Rancho Workload Dashboard
El Ranchero!

2021-10-08 14:35 UTC, nomadicoder commented on README.md
> +- Rancho Workload Dashboard
Fixed

2021-10-08 14:35 UTC, nomadicoder commented on README.md
> +1. In browser, visit the Rancho Workload Dashboard
Fixed

2021-10-08 14:41 UTC, sensei100 approved these changes

2021-10-08 14:41 UTC, merged